### PR TITLE
add TOC component

### PR DESCRIPTION
**Pull request by sw-yx**
adds @janosh's https://toc.janosh.dev

the design is not super yet (it should probably float on desktop?) so idk but i like the UX

references #112 

image

image

### CODE REVIEW

**Comment by janosh** [comment]
@sw-yx Thanks for the ping. Definitely agree the CSS could be improved. Happy to take suggestions! 👍

**Comment by sw-yx** [comment]
performance gets hits by 12 points

image



mobile styling not worked out yet

image

**Comment by sw-yx** [comment]
dont think its worth it yet. closing for now.

**Comment by sw-yx** [comment]
fwiw i belatedly realized that there were some conflicting factors (netlify injects some js inthe deploy preview by default that severely hits perf, have to turn off) that made the above comparison unfair. anyway i didnt like the styling so  the second attempt with svelte-put was better for me https://github.com/sw-yx/swyxkit/issues/165

**Pull request closed without merging**
