### PR TITLE
update to SvelteKit 330

### PR DESCRIPTION
**Pull request by sw-yx**
This PR is auto-generated by a nightly GitHub action.  It should automatically be merged if tests pass.

### CODE REVIEW

**Comment by sw-yx** [comment]
@georgeoffley this dependency update broke swyxkit - there is no longer any /blog page for some reason. mind taking a look if you are free?

**Comment by georgeoffley** [comment]
@sw-yx I got a mention about broken deps from this PR. Was that something you already took care of?

**Comment by sw-yx** [comment]
yes george! i went and fixed it myself since i had some time

**Comment by georgeoffley** [comment]
> yes george! i went and fixed it myself since i had some time

Awesome, thanks for letting me know!

**Pull request merged**
