### PR TITLE
add Dynamic OG images PR

### LINKED ISSUE #125: Dynamically generated og:images
maybe can steal from https://twitter.com/swyx/status/1579574976977698816

### PR DESCRIPTION
**Pull request by sw-yx**
closes #125

### CODE REVIEW

**Comment by sw-yx** [comment]
this PR is DOA unless https://github.com/yisibl/resvg-js/issues/175 is fixed

**Comment by sw-yx** [comment]
many thanks to https://github.com/geoffrich/sveltekit-satori-mdsvex-test and https://app.netlify.com/sites/lovely-blancmange-a2af75/deploys

**Comment by geoffrich** [comment]
Would anything in the netlify.toml be causing issues? Otherwise idk what's different between my repo and yours.

**Comment by sw-yx** [comment]
no idea. the only option i have left is a ground up rewrite to figure this out so i am leaving this til later haha

**Comment by sw-yx** [comment]
giving up on this for now since #161 is a good-enough if temporary solution

**Comment by ak4zh** [comment]
This one looks useful: https://github.com/etherCorps/sveltekit-og

**Pull request closed without merging**
